// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: exercises.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercises (
    id,
    name,
    tool
)
VALUES (
    gen_random_uuid(),
    $1,
    $2
)
RETURNING id, name, tool
`

type CreateExerciseParams struct {
	Name string `json:"name"`
	Tool string `json:"tool"`
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, createExercise, arg.Name, arg.Tool)
	var i Exercise
	err := row.Scan(&i.ID, &i.Name, &i.Tool)
	return i, err
}

const deleteExercise = `-- name: DeleteExercise :exec
DELETE FROM exercises
WHERE id = $1
`

func (q *Queries) DeleteExercise(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteExercise, id)
	return err
}

const getExercises = `-- name: GetExercises :many
SELECT id, name, tool FROM exercises
`

func (q *Queries) GetExercises(ctx context.Context) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, getExercises)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(&i.ID, &i.Name, &i.Tool); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSingleExercise = `-- name: GetSingleExercise :one
SELECT id, name, tool FROM exercises
WHERE id = $1
`

func (q *Queries) GetSingleExercise(ctx context.Context, id uuid.UUID) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, getSingleExercise, id)
	var i Exercise
	err := row.Scan(&i.ID, &i.Name, &i.Tool)
	return i, err
}

const updateExercise = `-- name: UpdateExercise :one
UPDATE exercises SET name = $2, tool = $3 
WHERE id = $1
RETURNING id, name, tool
`

type UpdateExerciseParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Tool string    `json:"tool"`
}

func (q *Queries) UpdateExercise(ctx context.Context, arg UpdateExerciseParams) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, updateExercise, arg.ID, arg.Name, arg.Tool)
	var i Exercise
	err := row.Scan(&i.ID, &i.Name, &i.Tool)
	return i, err
}
