// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Exercise struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Name      string    `json:"name"`
	Tool      string    `json:"tool"`
	UserID    uuid.UUID `json:"user_id"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	LastName  string    `json:"last_name"`
	FirstName string    `json:"first_name"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
}

type Workout struct {
	ID            uuid.UUID `json:"id"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	TotalDuration int32     `json:"total_duration"`
	UserID        uuid.UUID `json:"user_id"`
}

type WorkoutsExercise struct {
	ID          uuid.UUID `json:"id"`
	TimeSeconds int32     `json:"time_seconds"`
	WeightKg    int32     `json:"weight_kg"`
	WorkoutID   uuid.UUID `json:"workout_id"`
	ExerciseID  uuid.UUID `json:"exercise_id"`
}
