// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Exercise struct {
	ID     uuid.UUID `json:"id"`
	Name   string    `json:"name"`
	Tool   string    `json:"tool"`
	UserID uuid.UUID `json:"user_id"`
}

type Round struct {
	ID                uuid.UUID     `json:"id"`
	RoundNumber       int32         `json:"round_number"`
	RepsCompleted     float32       `json:"reps_completed"`
	WorkoutExerciseID uuid.NullUUID `json:"workout_exercise_id"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	LastName  string    `json:"last_name"`
	FirstName string    `json:"first_name"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
}

type Workout struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	TotalDuration int32     `json:"total_duration"`
	UserID        uuid.UUID `json:"user_id"`
}

type WorkoutSummary struct {
	WorkoutExerciseID uuid.NullUUID `json:"workout_exercise_id"`
	TotalReps         float32       `json:"total_reps"`
	WorkCapacity      float32       `json:"work_capacity"`
}

type WorkoutsExercise struct {
	ID          uuid.UUID `json:"id"`
	TimeSeconds int32     `json:"time_seconds"`
	WeightKg    float32   `json:"weight_kg"`
	WorkoutID   uuid.UUID `json:"workout_id"`
	ExerciseID  uuid.UUID `json:"exercise_id"`
}
